import json
import os
import urllib.parse
import webbrowser
from datetime import datetime
from http.server import BaseHTTPRequestHandler, HTTPServer

import pkce
import requests
from dotenv import load_dotenv

load_dotenv()

redirect_uri = "http://127.0.0.1:8000/callback"
scope = "user-read-private user-read-email user-library-read playlist-modify-public \
        playlist-modify-private"
code_verifier = pkce.generate_code_verifier(length=128)
code_challenge = pkce.get_code_challenge(code_verifier)


class RequestHandler(BaseHTTPRequestHandler):

    def log_message(self, format, *args):
        pass

    def log_error(self, format, *args):
        pass

    def log_request(self, code="-", size="-"):
        pass

    # Implementer use_case user refuse
    def do_GET(self):
        queries = urllib.parse.parse_qs(self.path)
        try:
            if "/callback?code" not in queries:
                raise KeyError("Connection to Spotify not authorized by user")
        except KeyError:
            self.send_response_only(200)
            self.end_headers()
            self.wfile.write(b"""<html>
            <head>
                    <title>Pacer Playlist Generator</title>
            </head>
            <body>
                    <h1>Authentification refused !</h1>
                 <p>You can close this page.</p>
         </body>
        </html>""")
            self.server.code = None
            return

        self.server.code = queries["/callback?code"]
        self.send_response_only(200)
        self.end_headers()
        self.wfile.write(b"""<html>
        <head>
                <title>Pacer Playlist Generator</title>
        </head>
        <body>
                <h1>Authentification Done !</h1>
             <p>You can close this page.</p>
     </body>
    </html>""")


def request_user_authorization():
    """PKCE Flow"""

    params = {
        # noqa : os.environ is prefered to os.getenv as if the CLIENT_ID is missing the error makes it obvious
        "client_id": os.environ["CLIENT_ID"],
        "response_type": "code",
        "redirect_uri": redirect_uri,
        "scope": scope,
        "code_challenge_method": "S256",
        "code_challenge": code_challenge,
    }

    base_url = "https://accounts.spotify.com/authorize"
    auth_url = f"{base_url}?{urllib.parse.urlencode(params)}"

    webbrowser.open(auth_url)

    server_address = ("127.0.0.1", 8000)
    with HTTPServer(server_address, RequestHandler) as callback_s:
        callback_s.handle_request()
        code = callback_s.code
    if code is None:
        raise KeyError("Connection to Spotify not authorized by user")
    return code


def request_access_token(code):
    data = {
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": redirect_uri,
        "client_id": os.environ["CLIENT_ID"],
        "code_verifier": code_verifier,
    }
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
    }
    r = requests.post(
        "https://accounts.spotify.com/api/token", data=data, headers=headers
    )
    if not r.ok:
        r.raise_for_status()
    else:
        return r.json()


def get_liked_songs(auth_tokens, i):

    headers = {
        "Authorization": "Bearer " + auth_tokens["access_token"],
    }
    r = requests.get(
        f"https://api.spotify.com/v1/me/tracks?offset={50*i}&limit=50", headers=headers
    )
    if not r.ok:
        r.raise_for_status()
    else:
        return r.json()["items"]


def create_new_playlist(auth_tokens):
    data = json.dumps(
        {
            "name": "Interval Training " + str(datetime.today()),
            "description": "Playlist for your interval training run generated by pacer \
            playlist generator",
            "public": False,
        }
    )
    headers = {
        "Authorization": "Bearer " + auth_tokens["access_token"],
        "Content-type": "application/json",
    }
    r = requests.post(
        "https://api.spotify.com/v1/me/playlists", data=data, headers=headers
    )
    if not r.ok:
        r.raise_for_status()
    else:
        return r


def add_matching_songs_to_new_playlist(auth_tokens, matching_songs, playlist_id):
    data = json.dumps(
        {
            "uris": matching_songs,
        }
    )
    headers = {
        "Authorization": "Bearer " + auth_tokens["access_token"],
        "Content-type": "application/json",
    }
    r = requests.post(
        f"https://api.spotify.com/v1/playlists/{playlist_id}/items",
        data=data,
        headers=headers,
    )
    if not r.ok:
        r.raise_for_status()
    else:
        return r
